pipeline:
  artifactory:
    image: athieriot/drone-artifactory
    url: http://54.169.222.113:8081/artifactory
    username: admin
    password: password
    pom: pom.xml
    files:
      - target/*.jar
      - target/*.war
